### PR TITLE
Jia hui Bug Fix v2.1

### LINKED ISSUE #94: [PE-D] The input requirements are inconsistent throughout the app.
The app is unclear on how unique the title must be.

Possible Case Scenario: 1 restaurant named INFinity and 1 movie named inFINity

However, when testing the `review` command, the app requires the user to input a case-sensitive title:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: CabbageTime/ped#4

### LINKED ISSUE #109: [PE-D] Missing "no such recommendation" prompt
It is stated in the user guide:
> Connoisseur will prompt you saying that no such recommendation exits.

However, when a non-existing recommendation is indicated, the prompt is missing.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: Emkay16/ped#6

### LINKED ISSUE #110: [PE-D] Value ranges for price range
While certain fields will notify the user of the valid character or value ranges (eg title has 20 character range, rating has value range of 0 - 5),

the value/character range is not stated for the price range for recommendations.

Perhaps it would be better to state a valid range for users to take note of, both in the product and in the user guide.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Emkay16/ped#7

### LINKED ISSUE #117: [PE-D] Price range does not accept decimal points
Even though the diagrams in the UG showed that the price range for recos can be displayed with decimal places for cents, the current iteration of the program does not allow it.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: fupernova/ped#7

### LINKED ISSUE #119: [PE-D] List command takes in unnecessary parameters
For listing in reco mode, adding random parameters behind the word `list` does not trigger any warnings. Its just a minor flaw, but would be nice to have a warning or error regarding syntax.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: fupernova/ped#9

### LINKED ISSUE #122: JSON exceptions
App crashes with invalid json formatting. Should catch these exceptions

### PR DESCRIPTION
**Pull request by jhjhajh**
Bug fix for feature bugs
Fix a typo in UG

### CODE REVIEW

File: src/main/java/seedu/connoisseur/commands/RecommendationList.java [hunk 1]
```diff
@@ -215,6 +215,14 @@ public void addRecommendationDetails() throws DuplicateException, EmptyInputExce
             try {
                 int priceFirst = Integer.parseInt(priceRange.split("-", 2)[0].trim());
                 int priceSecond = Integer.parseInt(priceRange.split("-", 2)[1].trim());
+                if (priceFirst < 0 || priceSecond < 0) {
```
Comment (Krithigha24) [inline src/main/java/seedu/connoisseur/commands/RecommendationList.java]: I think @EmilyTJX did changes for this alr, will there be merge conflicts?

**Review by Krithigha24 — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/connoisseur/commands/RecommendationList.java (hunk 1 above)
Comment (jhjhajh) [reply src/main/java/seedu/connoisseur/commands/RecommendationList.java]: hmm I think can merge emily's pr first? then i try to pull and fix merge conflicts. or the person merging can fix

**Review by huachen24 — APPROVED** [review]

**Review by Krithigha24 — APPROVED** [review]
